server:
  port: 9191

spring:
  cloud:
    aws:
      region:
        static: us-east-1
      s3:
        enabled: true
      credentials:
        access-key: AKIAWURHYOA4TLSHOONC
        secret-key: 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
logging:
  level:
    software.amazon.awssdk: DEBUG

discount:
  offer:
    price: 25